---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: add_data_service
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: maven
    script: |-
      #!/bin/bash
      mvn -B package
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      cd target
      cf push "${CF_APP}-blue" -n "${CF_APP}" -p "springboot-greetings-demo.war" -m 256M
      cf delete "${CF_APP}-green" -f
      cf rename "${CF_APP}-blue" "${CF_APP}-green"
      #Optionally, redeploy blue to be able to show they're both up and the green/blue process worked.
      cf push "${CF_APP}-blue" -n "${CF_APP}" -p "springboot-greetings-demo.war" -m 256M
      cf apps | grep "${CF_APP}"
      # View logs
      # cf logs "${CF_APP}" --recent
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publis
